AVP: 1
balance_losses: true
batch_norm: 1
batch_size: 4
data_dir: /home/julia/landmark_detection/paper/data/images/Cephalometric
device: cuda
evaluate_model_every: 1000
interlayers: null
learning_rate: 0.001
lr_decay: false
masked_loss: false
max_iters: 300000
n_convpairs: 2
n_downsampling: 4
network: resnet_34
output_directory: /home/julia/landmark_detection/rebuttal_final/experiments/Resnet34_balanced_rs123_AVP
prod_class: false
regr_loss: l1
regr_trans: log
rs: 123
sevxsev: true
store_model_every: 5000
weight_decay: false
