AVP: 1
balance_losses: true
batch_norm: 1
batch_size: 4
chunk_size: 64
data_dir: /home/julia/landmark_detection/paper/data/images/CCTA
device: cuda
evaluate_model_every: 1000
interlayers: null
learning_rate: 0.001
lm: -1
lr_decay: false
masked_loss: false
max_iters: 300000
n_convpairs: 2
n_downsampling: 2
n_resnetblocks: 4
network: resnet_34_real
output_directory: /home/julia/landmark_detection/rebuttal_final/experiments/Resnet34_real_2DS_4blocks_CCTA15_ML_balanced_AVP
prod_class: false
regr_loss: l1
regr_trans: log
rs: 123
sevxsev: true
single_lm: false
store_model_every: 5000
voxel_size: 1.5
weight_decay: false
