balance_losses: false
batch_norm: 1
batch_size: 4
data_augmentation: false
data_dir: /home/julia/landmark_detection/paper/data/images/Cephalometric
device: cuda
evaluate_model_every: 1000
interlayers: null
learning_rate: 0.001
lm: -1
log_loss: true
lr_decay: false
masked_loss: false
max_iters: 310000
model_file: null
n_convpairs: 2
n_downsampling: 2
n_resnetblocks: 4
network: ResnetRandC
output_directory: /home/julia/landmark_detection/rebuttal_final/experiments_finetuning/ResnetRandC_ML_Ceph_logloss
prod_class: false
rs: 123
sevxsev: false
store_model_every: 5000
voxel_size: 1.5
weight_decay: 0.0
